### ISSUE TITLE
Cloud Run Pickling Error

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#216]
On running for the cloud, the following error comes out:

2024-04-22 18:50:49 - aztec-design-digital-twin - INFO
PSuU Exploratory Run invoked at 2024-04-22 18:50:49.981376

2024-04-22 18:50:50 - aztec-design-digital-twin - INFO
PSuU Exploratory Run Dimensions: N_jobs=128, N_timesteps=10, N_sweeps=100, N_samples=5, N_trajectories=500, N_measurements=5,000

2024-04-22 18:50:50 - aztec-design-digital-twin - INFO
PSuU Exploratory Run starting at 2024-04-22 18:50:50.115471, (0:00:00.134095 since invoke)
Simulation Chunks: 100%|█████████████████████████| 4/4 [00:00<00:00, 110.20it/s]
Initializing configurations: 100%|███████████| 125/125 [00:00<00:00, 210.13it/s]
Initializing configurations: 100%|███████████| 125/125 [00:00<00:00, 209.54it/s]
Initializing configurations: 100%|███████████| 125/125 [00:00<00:00, 206.80it/s]
Initializing configurations: 100%|███████████| 125/125 [00:00<00:00, 203.85it/s]
Flattening results:   6%|█                  | 125/2250 [00:00<00:11, 180.48it/s]
Flattening results:   6%|█                  | 125/2250 [00:00<00:11, 179.07it/s]
Flattening results:   6%|█                  | 125/2250 [00:00<00:12, 175.90it/s]
Flattening results:   6%|█                  | 125/2250 [00:00<00:12, 175.67it/s]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/ec2-user/SageMaker/aztec-gddt/aztec_gddt/experiment.py", line 237, in run_chunk
    sim_df.to_pickle(output_filename)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/generic.py", line 3165, in to_pickle
    to_pickle(
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/io/pickle.py", line 111, in to_pickle
    pickle.dump(obj, handles.handle, protocol=protocol)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f49f978e170>: attribute lookup <lambda> on aztec_gddt.params failed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/SageMaker/aztec-gddt/aztec_gddt/__main__.py", line 111, in <module>
    main()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ec2-user/SageMaker/aztec-gddt/aztec_gddt/__main__.py", line 79, in main
    psuu_exploratory_run(N_jobs=n_jobs,
  File "/home/ec2-user/SageMaker/aztec-gddt/aztec_gddt/experiment.py", line 241, in psuu_exploratory_run
    Parallel(n_jobs=processes)(delayed(run_chunk)(i_chunk, sweep_params) for (i_chunk, sweep_params) in tqdm(args, desc='Simulation Chunks', total=len(split_dicts)))
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f49f978e170>: attribute lookup <lambda> on aztec_gddt.params failed

**Comment by SeanMcOwen** [comment]
It looks like it does not play nicely with some of the parameters that are mapped into it because they have functions, i.e. gas estimators.

Three possible solutions:
1. Only add in parameters used if the simulation dataframe has more than one value for it, although this does not solve the problem if there is sweeping over gas estimators.
2. Change the parameters to be a string that then references the functions, so that the actual class is not present in params, but rather a string pointing to which gas estimator or similar thing to pick
3. Add a post processing step that goes through certain problem columns and changes the classes to be strings based on a name in it or some deterministic way to label the data instead of having classes in there

**Comment by danlessa** [comment]
@SeanMcOwen solution 3 seems to be the most elegant, we should avoid complex types before exporting or serializing them.

One suggestion for the string representation is to use a combination of the function name (`f.__name__`), signature (`inspect.signature(f)`) and location (`inspect.getfile(f)`)

eg.

```python
from inspect import signature, getfile

def f(a: float, b: int = 0.0) -> str:
  return ""
  
print(f"{f.__name__}[{signature(f)}]|getfile(f)")
>>> f[(b: float, c: int = 0.0) -> str]|<stdin>
```
